name: CI

on:
  pull_request:

jobs:
  ci:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]
        os: [ ubuntu, windows ]

    name: ${{ matrix.python-version }} ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Nox
      run: pip install nox
    - name: Run Nox
      run: nox
    - name: Upload to CodeCov
      uses: codecov/codecov-action@v3
